### ISSUE TITLE
Reference to `global` causes compilation errors

### ISSUE THREAD

**Issue by hlovdal** [w8r/Leaflet.draw.drag#39]
Using Leaflet.draw.drag inside an Angular 14 project currently does not work. In the project I am trying to update to Angular 14 now, referencing `global` makes the unit tests timeout after 30 seconds. I have not tracked down what causes that, but even `console.log(global);` triggers this, however referencing `global` is a problem even in a small, "clean" project.

Minimal steps to reproduce:

```shell
$ ng new draw-drag-test
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
...
$ cd draw-drag-test/
$ npm install
...
$ ng test --watch=false
...
Chrome 106.0.0.0 (Windows 10): Executed 3 of 3 SUCCESS (0.251 secs / 0.223 secs)
TOTAL: 3 SUCCESS

$ npm install leaflet leaflet-draw leaflet-draw-drag
...
$ ng test --watch=false
Chrome 106.0.0.0 (Windows 10): Executed 3 of 3 SUCCESS (0.15 secs / 0.126 secs)
TOTAL: 3 SUCCESS

$ echo "import 'leaflet-draw-drag';" >> src/app/draw-drag.spec.ts
$ ng test --watch=false
...
Chrome 106.0.0.0 (Windows 10) ERROR
  An error was thrown in afterAll
  Uncaught ReferenceError: global is not defined
  ReferenceError: global is not defined
      at Object.5612 (http://localhost:9884/_karma_webpack_/webpack:/node_modules/leaflet-draw-drag/index.js:1:9)
      at __webpack_require__ (http://localhost:9884/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.7707 (http://localhost:9884/_karma_webpack_/main.js:90:75)
      at __webpack_require__ (http://localhost:9884/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at webpackContext (http://localhost:9884/_karma_webpack_/webpack:/src/ sync \.spec\.ts$:11:1)
      at Array.forEach (<anonymous>)
      at Module.4289 (http://localhost:9884/_karma_webpack_/webpack:/src/test.ts:26:16)
      at __webpack_require__ (http://localhost:9884/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9884/_karma_webpack_/main.js:182:48)
      at http://localhost:9884/_karma_webpack_/main.js:183:54
Chrome 106.0.0.0 (Windows 10): Executed 3 of 3 ERROR (0 secs / 0.227 secs)
Chrome 106.0.0.0 (Windows 10) ERROR
  An error was thrown in afterAll
  Uncaught ReferenceError: global is not defined
  ReferenceError: global is not defined
      at Object.5612 (http://localhost:9884/_karma_webpack_/webpack:/node_modules/leaflet-draw-drag/index.js:1:9)
      at __webpack_require__ (http://localhost:9884/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.7707 (http://localhost:9884/_karma_webpack_/main.js:90:75)
      at __webpack_require__ (http://localhost:9884/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at webpackContext (http://localhost:9884/_karma_webpack_/webpack:/src/ sync \.spec\.ts$:11:1)
      at Array.forEach (<anonymous>)
      at Module.4289 (http://localhost:9884/_karma_webpack_/webpack:/src/test.ts:26:16)
      at __webpack_require__ (http://localhost:9884/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9884/_karma_webpack_/main.js:182:48)
Chrome 106.0.0.0 (Windows 10): Executed 3 of 3 ERROR (0.264 secs / 0.227 secs)
```

So can you change

```javascript
var L = global.L || require('leaflet');
```

to just 

```javascript
var L = require('leaflet');
```

and make a new release?

**Comment by baarbaracrr** [comment]
I did the same like yoo and i have the next error:
<img width="548" alt="image" src="https://user-images.githubusercontent.com/31986084/207859140-fefa440d-7b61-4785-9c39-05fcea054a56.png">

The error that I show you occurs when I do dragend.
And, on the other hand, when I drag the polygon, its data remains the same, its position does not change (getBounds()).

**Comment by hlovdal** [comment]
@baarbaracrr As a temporary workaround you can run

```shell
sed -i 's/global\./globalThis./' node_modules/leaflet-draw-drag/index.js
```

although this have a high chance of being reset when `npm install` is run. So probably the best approach is to add this command to all the relevant build/test/lint script entries in package.json.

**Comment by w8r** [comment]
@baarbaracrr you are just using a wrong version of Leaflet
