### ISSUE TITLE
Uncaught TypeError: L.DomEvent.fakeStop is not a function

### ISSUE THREAD

**Issue by jet112** [w8r/Leaflet.draw.drag#48]
There is a problem in Google Chrome.
When stop object drugging, two errors fires in Leaflet.Path.Drag module and map stays with disabled dragging.

```
Uncaught TypeError: L.DomEvent.fakeStop is not a function
    at NewClass._onDragEnd (Path.Drag.js:190:29)
    at HTMLDocument.handler (leaflet-src.js:2553:17)
    
Uncaught TypeError: L.DomEvent.skipped is not a function
    at NewClass.eval (Path.Drag.js:179:20)
```

This errors occurs because old version of Leaflet.Path.Drag module in dependency ("leaflet-path-drag": "^1.1.0").
It will be great if you will update dependency to: "leaflet-path-drag": "^1.8.0-beta.3" and publish this in npm.

**Comment by daric81** [comment]
I'm having exactly the same issue as @jet112. Are there any plans to bump leaflet-path-drag to 1.8.0-beta.3 as my app is broken ? 
Thanks

**Comment by jet112** [comment]
@daric81 here is the way to solve problem:

1. Create component with userMapEvent hook: 
```
const MapDrawDragFix = () => {
  const map = useMapEvent('mouseup', () => {
      map.dragging.enable()
  } );

  return null
}
```

2. Then place this component into MapContainer:

```
<MapContainer>
   <MapDrawDragFix />
   ...
</MapContainer>
```

So, you will see error in console, but map dragging will work :)

**Comment by daric81** [comment]
Nice workaround @jet112 in the meantime. Thanks!
